name: Lint with ruff

on:
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

      - name : Run ruff
        run: ruff check --fix --exit-non-zero-on-fix

      - name: Install Taplo CLI
        run: |
          curl -sSf https://taplo.tamasfe.dev/install.sh | sh
          echo "$HOME/.taplo/bin" >> $GITHUB_PATH

      - name: Check .toml formatting with Taplo
        run: taplo fmt --check
