# Run pytests with mypy, doctests, and coverage inside DUNE Container
name: Test, Type Check, and Coverage

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    # Natively run the entire job inside the DUNE DAQ container
    container:
      image: ghcr.io/dune-daq/nightly-release-alma9:development_v5

    steps:
      - name: Setup CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v5
        with:
          cvmfs_repositories: 'dunedaq.opensciencegrid.org,dunedaq-development.opensciencegrid.org'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dev nightly
        if: ${{ !cancelled() }}
        run: |
          mkdir nightly
          cd nightly
          source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
          setup_dbt latest_v5
          dbt-create -n last_fddaq
          cd NFD_DEV*
          source env.sh
          dbt-build
          dbt-workarea-env

      - name: Install package dependencies
        if: success()
        run: |
          # Source your environment first
          cd nightly/NFD_DEV* || true
          source env.sh
          
          # Navigate back to your root workspace folder and install package under test
          cd $GITHUB_WORKSPACE
          python -m pip install --upgrade pip
          pip install .[test]

      - name: Run tests, mypy, and generate coverage
        if: success()
        run: |
          cd nightly/NFD_DEV* || true
          source env.sh
          
          cd $GITHUB_WORKSPACE
          pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml