# Run pytests with mypy, doctests, and coverage inside DUNE Container
name: Test, Type Check, and Coverage

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    # Natively run the entire job inside the DUNE DAQ container
    container:
      image: ghcr.io/dune-daq/nightly-release-alma9:development_v5

    steps:
      - name: Set up dev nightly
        if: ${{ !cancelled() }}
        run: |
          mkdir nightly
          cd nightly
          source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
          setup_dbt latest_v5
          dbt-create -n last_fddaq

      - name: Setup Python environment, install package, and run tests
        if: success()
        run: |
          # Source your environment first
          cd nightly/NFD_DEV*
          source env.sh
          
          # Navigate back to your root workspace folder and install package under test
          cd pythoncode
          git clone https://github.com/${{ github.event.pull_request.head.repo.owner.login }}/daqpytools.git -b ${{ github.head_ref }} ||  git clone https://github.com/DUNE-DAQ/daqpytools.git -b ${{ github.head_ref }} 
          cd $GITHUB_WORKSPACE
          cd daqpytools
          python -m pip install --upgrade pip
          pip install .[test]

          pytest --junitxml=junit/test-results.xml --cov=drunc --cov-report=html

      - name: Publish JUnit test report
        uses: mikepenz/action-junit-report@v5
        if: ${{ !cancelled() }}
        with:
          report_paths: '${{ env.DRUNC_DIR }}/junit/test-results.xml'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml